## This file is automaticaly created ##
INCOPT = -I../../include
INST_DIR = /home/pub/bin/
CCWOPT = -w2
CCOPOPT = -O2
CCLINKOPT = -lm
ICCWOPT = -w1
ICCOPOPT = -O2
ICCLINKOPT = -lm
GCCWOPT = -Wall
GCCOPOPT = -O3
GCCLINKOPT = -lm
CCOPT = $(CCWOPT) $(CCOPOPT) $(CCLINKOPT)
GCCOPT = $(GCCWOPT) $(GCCOPOPT) $(GCCLINKOPT)
ICCOPT = $(ICCWOPT)
OMPOPT = 
CC = gcc
OPT =  $(GCCOPT) $(INCOPT)
