#!/bin/bash
#PBS -N mpi_normal_no60
#PBS -q large
#PBS -l walltime=2:00:00
#PBS -j oe
#PBS -l select=8:ncpus=24:mpiprocs=24

cd $PBS_O_WORKDIR
module load openmpi/gnu/3.1.3
_NPROCS=`cat $PBS_NODEFILE | wc -l`
mpirun -n $_NPROCS /home/kamano/gitsrc/SOC/SOC_0.5.10-01/soc-lm sf=/home/kamano/gitsrc/SOC/SOC_0.5.10-01/test-data/test_matrix_2000.sv cf=/home/kamano/gitsrc/SOC/SOC_0.5.10-01/test-data/test_matrix_2000.cv.20.C > /home/kamano/gitsrc/SOC/SOC_0.5.10-01/test-data/out.20190711
